// Generated from Sources/SwifterKit/DriverKit/Runtime/RuntimeSchema.swift. Do not edit.
// Regenerate: SWIFTERKIT_UPDATE_SCHEMA=1 swift test --filter RuntimeSchemaTests

#ifndef SwifterKitRuntimeSchema_h
#define SwifterKitRuntimeSchema_h

#include <stdint.h>

static constexpr uint32_t kSwifterKitRuntimeMagic = 0x53574B54;
static constexpr uint16_t kSwifterKitRuntimeVersionMinimum = 2;
static constexpr uint16_t kSwifterKitRuntimeVersionMaximum = 2;
static constexpr uint32_t kSwifterKitRuntimeMaximumMessageSize = 65536;
static constexpr uint32_t kSwifterKitRuntimeHeaderSize = 24;
static constexpr uint32_t kSwifterKitRuntimeCommandHeaderSize = 16;
static constexpr uint32_t kSwifterKitRuntimeHandshakeRequestSize = 8;
static constexpr uint32_t kSwifterKitRuntimeHandshakeResponseSize = 16;

static constexpr uint32_t kSwifterKitMessageFlagExpectsResponse = 0x1;

static constexpr uint64_t kSwifterKitSelectorTransact = 0;
static constexpr uint64_t kSwifterKitSelectorEventNotification = 1;

static constexpr uint64_t kSwifterKitCapabilityMemory = 0x1;
static constexpr uint64_t kSwifterKitCapabilityInterrupts = 0x2;
static constexpr uint64_t kSwifterKitCapabilityUSB = 0x4;
static constexpr uint64_t kSwifterKitCapabilityHID = 0x8;
static constexpr uint64_t kSwifterKitCapabilityPCI = 0x10;
static constexpr uint64_t kSwifterKitCapabilitySerial = 0x20;
static constexpr uint64_t kSwifterKitCapabilityNetworking = 0x40;
static constexpr uint64_t kSwifterKitCapabilityAudio = 0x80;
static constexpr uint64_t kSwifterKitCapabilityMIDI = 0x100;
static constexpr uint64_t kSwifterKitCapabilityBlockStorage = 0x200;
static constexpr uint64_t kSwifterKitCapabilitySCSI = 0x400;
static constexpr uint64_t kSwifterKitCapabilityVideo = 0x800;

enum class SwifterKitRuntimeMessageKind : uint16_t {
    Handshake = 1,
    Command = 2,
    Response = 3,
    Event = 4,
    Error = 5,
};

enum class SwifterKitRuntimeOpcode : uint32_t {
    Ping = 0x0000,
    PollEvent = 0x0001,
    InterruptSetEnabled = 0x0100,
    InterruptGetType = 0x0101,
    InterruptGetLast = 0x0102,
    USBControlTransfer = 0x0200,
    USBPipeTransfer = 0x0201,
    USBClearStall = 0x0202,
    USBSelectAlternateSetting = 0x0203,
    USBDeviceSetConfiguration = 0x0210,
    USBDeviceReset = 0x0211,
    USBGetDeviceSpeed = 0x0212,
    USBGetDeviceAddress = 0x0213,
    USBGetPortStatus = 0x0214,
    USBGetFrameNumber = 0x0215,
    USBGetCurrentMicroframe = 0x0216,
    USBGetReferenceMicroframe = 0x0217,
    USBCopyDeviceDescriptor = 0x0218,
    USBCopyConfigurationDescriptor = 0x0219,
    USBCopyStringDescriptor = 0x021A,
    USBCopyCapabilityDescriptors = 0x021B,
    USBCopyDescriptor = 0x021C,
    USBCopyInterfaces = 0x021D,
    USBCopyInterfaceDescriptor = 0x021E,
    USBSetIdlePolicy = 0x021F,
    USBGetIdlePolicy = 0x0220,
    USBAbortDeviceRequests = 0x0221,
    USBPipeAsyncIO = 0x0230,
    USBPipeAbort = 0x0231,
    USBPipeSetIdlePolicy = 0x0232,
    USBPipeGetIdlePolicy = 0x0233,
    USBPipeGetDescriptors = 0x0234,
    USBPipeGetSpeed = 0x0235,
    USBPipeGetDeviceAddress = 0x0236,
    USBPipeIsochIO = 0x0237,
    USBAsyncDeviceRequest = 0x0240,
    USBPipeCreateBundleRing = 0x0250,
    USBPipeEnqueueBundled = 0x0251,
    USBPipeReleaseBundleRing = 0x0252,
    USBPipeAdjust = 0x0260,
    HIDSubmitInputReport = 0x0300,
    HIDGetRuntimeStatistics = 0x0301,
    HIDCompleteGetReport = 0x0310,
    HIDCopyElements = 0x0311,
    HIDGetElementValue = 0x0312,
    HIDSetElementValue = 0x0313,
    HIDCommitElement = 0x0314,
    HIDCommitElements = 0x0315,
    HIDElementConformsTo = 0x0316,
    HIDInterfaceGetReport = 0x0317,
    HIDInterfaceSetReport = 0x0318,
    HIDInterfaceProcessReport = 0x0319,
    HIDDispatchKeyboard = 0x0320,
    HIDDispatchRelativePointer = 0x0321,
    HIDDispatchAbsolutePointer = 0x0322,
    HIDDispatchScroll = 0x0323,
    HIDDispatchDigitizerStylus = 0x0324,
    HIDDispatchDigitizerTouches = 0x0325,
    HIDDispatchDigitizerCollection = 0x0326,
    HIDDispatchGameController = 0x0327,
    HIDDispatchExtendedGameController = 0x0328,
    HIDSetLED = 0x0329,
    HIDSetLEDState = 0x032A,
    HIDServiceConformsTo = 0x032B,
    HIDSetEventDriverCategories = 0x032C,
    HIDDeviceGetReport = 0x0330,
    HIDDeviceSetProtocol = 0x0331,
    HIDDeviceSetIdle = 0x0332,
    HIDDeviceSetIdlePolicy = 0x0333,
    HIDDeviceReset = 0x0334,
    PCIRead = 0x0400,
    PCIWrite = 0x0401,
    PCIGetBARInfo = 0x0402,
    PCIGetLocation = 0x0403,
    PCIFindCapability = 0x0404,
    PCIReset = 0x0410,
    PCISaveDeviceState = 0x0411,
    PCIRestoreDeviceState = 0x0412,
    PCIHasPowerManagement = 0x0413,
    PCIEnablePowerManagement = 0x0414,
    PCIGetLinkSpeed = 0x0415,
    PCISetLinkSpeed = 0x0416,
    PCISetASPMState = 0x0417,
    PCISetProperties = 0x0418,
    MemoryAllocate = 0x0500,
    MemoryRelease = 0x0501,
    MemorySetLength = 0x0502,
    MemoryRead = 0x0503,
    MemoryWrite = 0x0504,
    MemoryGetInfo = 0x0505,
    MemoryPrepareDMA = 0x0506,
    MemoryCompleteDMA = 0x0507,
    MemorySubrange = 0x0508,
    MemoryChain = 0x0509,
    MemoryWrapClient = 0x050A,
    SerialEnqueueReceive = 0x0600,
    SerialDequeueTransmit = 0x0601,
    SerialSetModemStatus = 0x0602,
    SerialReportReceiveErrors = 0x0603,
    BlockStorageComplete = 0x0700,
    BlockStorageCompleteIO = 0x0701,
    MIDISend = 0x0800,
    MIDIGetObjectInfo = 0x0810,
    MIDISetObjectName = 0x0811,
    MIDIGetPropertyType = 0x0812,
    MIDICopyProperty = 0x0813,
    MIDISetProperty = 0x0814,
    MIDIGetProperties = 0x0815,
    MIDISetProperties = 0x0816,
    MIDIGetDeviceState = 0x0817,
    MIDIGetEntityMembers = 0x0818,
    MIDISetMemberAttachment = 0x0819,
    NetworkReceive = 0x0900,
    NetworkCompleteTransmit = 0x0901,
    NetworkReportLink = 0x0902,
    NetworkReportLinkQuality = 0x0910,
    NetworkReportDataBandwidths = 0x0911,
    NetworkAddHardwareCounts = 0x0912,
    NetworkReportNICProxyLimits = 0x0913,
    NetworkSetPolling = 0x0914,
    NetworkSetPollerParameters = 0x0915,
    NetworkReceivePackets = 0x0920,
    NetworkCompleteTransmits = 0x0921,
    NetworkSetQueueEnabled = 0x0922,
    NetworkPurgeTransmitQueue = 0x0923,
    NetworkServiceTransmitQueue = 0x0924,
    NetworkCompleteInterfaceCommand = 0x0925,
    AudioReadStream = 0x0A00,
    AudioWriteStream = 0x0A01,
    AudioGetIOState = 0x0A02,
    AudioUpdateTimestamp = 0x0A03,
    AudioRequestSampleRate = 0x0A04,
    AudioGetControl = 0x0A05,
    AudioSetControl = 0x0A06,
    AudioGetCustomProperty = 0x0A07,
    AudioSetCustomProperty = 0x0A08,
    AudioGetObjectInfo = 0x0A10,
    AudioSetObjectName = 0x0A11,
    AudioGetElementName = 0x0A12,
    AudioSetElementName = 0x0A13,
    AudioPropertiesChanged = 0x0A14,
    AudioGetBoxState = 0x0A15,
    AudioSetBoxProperty = 0x0A16,
    AudioSetBoxOwnership = 0x0A17,
    AudioGetClockDeviceState = 0x0A18,
    AudioSetClockDeviceProperty = 0x0A19,
    AudioSetClockSampleRates = 0x0A1A,
    AudioUpdateClockTimestamp = 0x0A1B,
    AudioRequestClockSampleRate = 0x0A1C,
    AudioCompleteRequest = 0x0A1D,
    AudioGetDeviceState = 0x0A20,
    AudioSetDeviceProperty = 0x0A21,
    AudioSetPreferredChannelLayout = 0x0A22,
    AudioGetStreamState = 0x0A23,
    AudioSetStreamProperty = 0x0A24,
    AudioGetControlInfo = 0x0A25,
    AudioSetControlProperty = 0x0A26,
    AudioRemoveSelectorItems = 0x0A27,
    AudioGetCustomPropertyInfo = 0x0A28,
    AudioSetMemberAttachment = 0x0A29,
    SCSICompleteParallelTask = 0x0B00,
    SCSITargetPresent = 0x0B20,
    SCSICreateTarget = 0x0B21,
    SCSIDestroyTarget = 0x0B22,
    SCSISetControllerProperties = 0x0B23,
    SCSIRemoveControllerProperties = 0x0B24,
    SCSISetTargetProperties = 0x0B25,
    SCSIRemoveTargetProperties = 0x0B26,
    SCSIMediaParametersChanged = 0x0B27,
    SCSIReadTaskData = 0x0B28,
    SCSIWriteTaskData = 0x0B29,
    SCSIPeripheralSendCDB = 0x0B10,
    SCSIPeripheralSuspendServices = 0x0B11,
    SCSIPeripheralResumeServices = 0x0B12,
    SCSIPeripheralReset = 0x0B13,
    SCSIPeripheralReportMediumBlockSize = 0x0B14,
    VideoReadBuffer = 0x0C00,
    VideoWriteBuffer = 0x0C01,
    VideoEnqueueOutput = 0x0C02,
    VideoDequeueInput = 0x0C03,
    VideoNotifyOutput = 0x0C04,
    VideoUpdateTimestamp = 0x0C05,
    VideoRequestSampleRate = 0x0C06,
    VideoGetControl = 0x0C07,
    VideoSetControl = 0x0C08,
    VideoGetCustomProperty = 0x0C09,
    VideoSetCustomProperty = 0x0C0A,
    VideoGetObjectInfo = 0x0C10,
    VideoSetObjectName = 0x0C11,
    VideoGetElementName = 0x0C12,
    VideoSetElementName = 0x0C13,
    VideoPropertiesChanged = 0x0C14,
    VideoGetBoxState = 0x0C15,
    VideoSetBoxProperty = 0x0C16,
    VideoSetBoxOwnership = 0x0C17,
    VideoGetClockDeviceState = 0x0C18,
    VideoSetClockDeviceProperty = 0x0C19,
    VideoSetClockSampleRates = 0x0C1A,
    VideoUpdateClockTimestamp = 0x0C1B,
    VideoRequestClockSampleRate = 0x0C1C,
    VideoCompleteRequest = 0x0C1D,
    VideoNotifyBufferQueue = 0x0C1E,
    VideoSetCustomPropertyOwner = 0x0C1F,
    VideoGetDeviceState = 0x0C20,
    VideoSetDeviceProperty = 0x0C21,
    VideoSetPreferredChannelLayout = 0x0C22,
    VideoGetStreamState = 0x0C23,
    VideoSetStreamProperty = 0x0C24,
    VideoGetBufferInfo = 0x0C25,
    VideoSetBufferProperty = 0x0C26,
    VideoGetControlInfo = 0x0C27,
    VideoSetControlProperty = 0x0C28,
    VideoRemoveSelectorItems = 0x0C29,
    VideoGetCustomPropertyInfo = 0x0C2A,
    VideoSetMemberAttachment = 0x0C2B,
    VideoEnqueueOutputBuffer = 0x0C2C,
    VideoGetStreamMemoryObjectID = 0x0C2D,
    ServiceSetProperties = 0x0D00,
    ServiceCopyProperties = 0x0D01,
    ServiceRemoveProperty = 0x0D02,
    ServiceSearchProperty = 0x0D03,
    ServiceCopyProviderProperties = 0x0D04,
    ServiceCopyName = 0x0D05,
    ServiceGetRegistryEntryID = 0x0D06,
    ServiceChangePowerState = 0x0D10,
    ServiceSetPowerOverride = 0x0D11,
    ServiceCreatePMAssertion = 0x0D12,
    ServiceReleasePMAssertion = 0x0D13,
    ServiceCompletePowerState = 0x0D14,
    ServiceAdjustBusy = 0x0D20,
    ServiceGetBusyState = 0x0D21,
    ServiceRequireMaxBusStall = 0x0D22,
    ServiceTerminate = 0x0D23,
    ServiceCopySystemStateItem = 0x0D30,
    ServiceCreateSystemStateItem = 0x0D31,
    ServiceSetSystemStateItem = 0x0D32,
    ServiceSendCoreAnalyticsEvent = 0x0D33,
    TimerStart = 0x0E00,
    TimerCancel = 0x0E01,
    WatchServices = 0x0E10,
    WatchSystemState = 0x0E11,
    WatchCancel = 0x0E12,
    ReporterUpdate = 0x0E20,
    ReporterRead = 0x0E21,
    FastPathRun = 0x0F00,
    FastPathStatus = 0x0F01,
    FastPathDataQueueNotify = 0x0F02,
};

static constexpr uint32_t kSwifterKitEventInterrupt = 0x0100;
static constexpr uint32_t kSwifterKitEventUSBPipeIO = 0x0200;
static constexpr uint32_t kSwifterKitEventUSBPipeIsochIO = 0x0201;
static constexpr uint32_t kSwifterKitEventUSBDeviceRequest = 0x0210;
static constexpr uint32_t kSwifterKitEventUSBPipeBundledIO = 0x0220;
static constexpr uint32_t kSwifterKitEventHIDReport = 0x0300;
static constexpr uint32_t kSwifterKitEventHIDInputReport = 0x0310;
static constexpr uint32_t kSwifterKitEventHIDElementValues = 0x0311;
static constexpr uint32_t kSwifterKitEventHIDGetReportRequest = 0x0312;
static constexpr uint32_t kSwifterKitEventHIDLEDState = 0x0313;
static constexpr uint32_t kSwifterKitEventHIDProperties = 0x0314;
static constexpr uint32_t kSwifterKitEventSerial = 0x0600;
static constexpr uint32_t kSwifterKitEventUSBSerialPacket = 0x0610;
static constexpr uint32_t kSwifterKitEventBlockStorage = 0x0700;
static constexpr uint32_t kSwifterKitEventMIDI = 0x0800;
static constexpr uint32_t kSwifterKitEventNetwork = 0x0900;
static constexpr uint32_t kSwifterKitEventAudio = 0x0A00;
static constexpr uint32_t kSwifterKitEventAudioObject = 0x0A01;
static constexpr uint32_t kSwifterKitEventSCSIParallelTask = 0x0B00;
static constexpr uint32_t kSwifterKitEventSCSIManagement = 0x0B01;
static constexpr uint32_t kSwifterKitEventSCSITargetCreated = 0x0B02;
static constexpr uint32_t kSwifterKitEventVideo = 0x0C00;
static constexpr uint32_t kSwifterKitEventVideoObject = 0x0C01;
static constexpr uint32_t kSwifterKitEventServicePowerState = 0x0D00;
static constexpr uint32_t kSwifterKitEventTimer = 0x0E00;
static constexpr uint32_t kSwifterKitEventWatchServices = 0x0E10;
static constexpr uint32_t kSwifterKitEventWatchSystemState = 0x0E11;
static constexpr uint32_t kSwifterKitEventFastPath = 0x0F00;
static constexpr uint32_t kSwifterKitEventFastPathDataQueue = 0x0F01;

static constexpr uint32_t kSwifterKitMaximumTimers = 16;
static constexpr uint32_t kSwifterKitMaximumServiceWatches = 8;
static constexpr uint32_t kSwifterKitMaximumWatchedStateItems = 8;
static constexpr uint64_t kSwifterKitTimerMinimumIntervalNanoseconds = 1000000ULL;
static constexpr uint64_t kSwifterKitTimerMaximumNanoseconds = 86400000000000ULL;

enum class SwifterKitServiceWatchKind : uint32_t {
    Terminated = 0,
    Matched = 1,
};

static constexpr uint32_t kSwifterKitMaximumReporters = 16;
static constexpr uint32_t kSwifterKitMaximumReportChannels = 32;
static constexpr uint32_t kSwifterKitMaximumReportStates = 16;
static constexpr uint32_t kSwifterKitMaximumHistogramSegments = 8;
static constexpr uint32_t kSwifterKitMaximumHistogramBuckets = 128;

enum class SwifterKitReporterKind : uint32_t {
    Simple = 1,
    State = 2,
    Histogram = 3,
};

enum class SwifterKitReporterOperation : uint32_t {
    SetValue = 1,
    IncrementValue = 2,
    SetState = 3,
    OverrideState = 4,
    IncrementState = 5,
    TallyValue = 6,
    OverrideBucket = 7,
};

enum class SwifterKitPropertyTag : uint8_t {
    Boolean = 1,
    Number = 2,
    String = 3,
    Data = 4,
    Array = 5,
    Dictionary = 6,
};
static constexpr uint32_t kSwifterKitPropertyMaximumDepth = 8;
static constexpr uint32_t kSwifterKitPropertyNameMaximumLength = 127;

enum class SwifterKitSCSIManagementKind : uint32_t {
    InitializeTarget = 1,
    AbortTask = 2,
    AbortTaskSet = 3,
    ClearACA = 4,
    ClearTaskSet = 5,
    LogicalUnitReset = 6,
    TargetReset = 7,
};
static constexpr uint32_t kSwifterKitSCSIMaximumPropertyCount = 32;
static constexpr uint32_t kSwifterKitSCSIMaximumFeatureRequests = 5;
static constexpr uint32_t kSwifterKitSCSICommandDescriptorBlockMaximumSize = 16;
static constexpr uint32_t kSwifterKitSCSIPeripheralMaximumDataLength = 61440;
static constexpr uint16_t kSwifterKitSCSIPropertyKeyMaximumLength = 127;
static constexpr uint16_t kSwifterKitSCSIPropertyValueMaximumLength = 1024;

enum class SwifterKitBlockStorageRequestKind : uint32_t {
    Eject = 1,
    Synchronize = 2,
    Unmap = 3,
    Read = 4,
    Write = 5,
};

enum class SwifterKitSerialEventKind : uint32_t {
    Activate = 1,
    Deactivate = 2,
    ReceiveSpaceAvailable = 3,
    TransmitDataAvailable = 4,
    ResetFIFO = 5,
    SendBreak = 6,
    ProgramUART = 7,
    ProgramBaudRate = 8,
    ProgramModemControl = 9,
    ProgramLatencyTimer = 10,
    ProgramFlowControl = 11,
};

enum class SwifterKitUSBSerialPacketKind : uint32_t {
    Received = 1,
    Interrupt = 2,
};

enum class SwifterKitMIDIEventKind : uint32_t {
    StartIO = 1,
    StopIO = 2,
    Received = 3,
};

static constexpr uint32_t kSwifterKitMIDITargetDriver = 0;
static constexpr uint32_t kSwifterKitMIDITargetDevice = 1;
static constexpr uint32_t kSwifterKitMIDITargetEntity = 2;
static constexpr uint32_t kSwifterKitMIDITargetSource = 3;
static constexpr uint32_t kSwifterKitMIDITargetDestination = 4;
static constexpr uint32_t kSwifterKitMIDITargetObject = 5;
static constexpr uint32_t kSwifterKitMIDIKeySelector = 0;
static constexpr uint32_t kSwifterKitMIDIKeyString = 1;
static constexpr uint32_t kSwifterKitMIDIDriverClass = 0xFFFFFFFF;
static constexpr uint32_t kSwifterKitMIDIMaximumListedObjects = 64;
static constexpr uint32_t kSwifterKitMIDINameMaximumLength = 255;

static constexpr uint32_t kSwifterKitMIDIValueString = 0;
static constexpr uint32_t kSwifterKitMIDIValueNumber = 1;
static constexpr uint32_t kSwifterKitMIDIValueDictionary = 2;
static constexpr uint32_t kSwifterKitMIDIValueData = 3;
static constexpr uint32_t kSwifterKitMIDIValueArray = 4;
static constexpr uint32_t kSwifterKitMIDIPropertyMaximumDepth = 4;
static constexpr uint32_t kSwifterKitMIDIPropertyMaximumEntries = 256;
static constexpr uint32_t kSwifterKitMIDIPropertyKeyMaximumLength = 255;

static constexpr uint32_t kSwifterKitUSBMaximumInterfaces = 256;
static constexpr uint32_t kSwifterKitUSBMaximumPendingTransfers = 32;
static constexpr uint32_t kSwifterKitUSBMaximumIsochronousFrames = 1024;
static constexpr uint32_t kSwifterKitUSBMaximumBundleRings = 4;
static constexpr uint32_t kSwifterKitUSBMaximumBundleRingEntries = 64;
static constexpr uint32_t kSwifterKitUSBMaximumBundleRingBytes = 4194304;
static constexpr uint32_t kSwifterKitUSBMaximumBundledTransfers = 16;
static constexpr uint16_t kSwifterKitUSBSupportedReleases[] =
    {0x0110, 0x0200, 0x0210, 0x0300, 0x0310, 0x0320};

static constexpr uint8_t kSwifterKitUSBConfigurationCurrent = 0;
static constexpr uint8_t kSwifterKitUSBConfigurationIndex = 1;
static constexpr uint8_t kSwifterKitUSBConfigurationValue = 2;
static constexpr uint8_t kSwifterKitUSBPipeDescriptorsOriginal = 0;
static constexpr uint8_t kSwifterKitUSBPipeDescriptorsCurrentPolicy = 1;

static constexpr uint32_t kSwifterKitHIDMaximumPendingReports = 16;
static constexpr uint32_t kSwifterKitHIDMaximumElementPage = 512;
static constexpr uint32_t kSwifterKitHIDMaximumCookies = 1024;
static constexpr uint32_t kSwifterKitHIDMaximumCollectionElements = 64;
static constexpr uint32_t kSwifterKitHIDMaximumTouches = 64;
static constexpr uint32_t kSwifterKitHIDMaximumEventValues = 256;
static constexpr uint32_t kSwifterKitHIDLEDUsagePage = 0x08;

enum class SwifterKitHIDElementWriteKind : uint32_t {
    Value = 0,
    Data = 1,
};

static constexpr uint32_t kSwifterKitHIDHostReportOutput = 0x1;
static constexpr uint32_t kSwifterKitHIDHostReportFeature = 0x2;
static constexpr uint32_t kSwifterKitHIDHostReportTypesAll = 0x3;
static constexpr uint32_t kSwifterKitHIDGetReportInput = 0x1;
static constexpr uint32_t kSwifterKitHIDGetReportOutput = 0x2;
static constexpr uint32_t kSwifterKitHIDGetReportFeature = 0x4;
static constexpr uint32_t kSwifterKitHIDGetReportTypesAll = 0x7;
static constexpr uint32_t kSwifterKitHIDDeliverReports = 0x1;
static constexpr uint32_t kSwifterKitHIDDeliverElementValues = 0x2;
static constexpr uint32_t kSwifterKitHIDDeliverAll = 0x3;

static constexpr uint32_t kSwifterKitHIDEventDriverCategoryKeyboard = 0x1;
static constexpr uint32_t kSwifterKitHIDEventDriverCategoryPointer = 0x2;
static constexpr uint32_t kSwifterKitHIDEventDriverCategoryScroll = 0x4;
static constexpr uint32_t kSwifterKitHIDEventDriverCategoryLED = 0x8;
static constexpr uint32_t kSwifterKitHIDEventDriverCategoryDigitizer = 0x10;
static constexpr uint32_t kSwifterKitHIDEventDriverCategoryProximity = 0x20;
static constexpr uint32_t kSwifterKitHIDEventDriverCategoryGameController = 0x40;
static constexpr uint32_t kSwifterKitHIDEventDriverCategoryRemaining = 0x80;
static constexpr uint32_t kSwifterKitHIDEventDriverCategoriesAll = 0xFF;

static constexpr uint32_t kSwifterKitHIDStylusInRange = 0x1;
static constexpr uint32_t kSwifterKitHIDStylusTip = 0x2;
static constexpr uint32_t kSwifterKitHIDStylusBarrelSwitch = 0x4;
static constexpr uint32_t kSwifterKitHIDStylusInvert = 0x8;
static constexpr uint32_t kSwifterKitHIDStylusEraser = 0x10;
static constexpr uint32_t kSwifterKitHIDStylusTipChanged = 0x20;
static constexpr uint32_t kSwifterKitHIDStylusPositionChanged = 0x40;
static constexpr uint32_t kSwifterKitHIDStylusRangeChanged = 0x80;
static constexpr uint32_t kSwifterKitHIDStylusFlagsAll = 0xFF;
static constexpr uint32_t kSwifterKitHIDTouchInRange = 0x1;
static constexpr uint32_t kSwifterKitHIDTouchTouch = 0x2;
static constexpr uint32_t kSwifterKitHIDTouchTouchValid = 0x4;
static constexpr uint32_t kSwifterKitHIDTouchTouchChanged = 0x8;
static constexpr uint32_t kSwifterKitHIDTouchPositionChanged = 0x10;
static constexpr uint32_t kSwifterKitHIDTouchRangeChanged = 0x20;
static constexpr uint32_t kSwifterKitHIDTouchFlagsAll = 0x3F;
static constexpr uint32_t kSwifterKitHIDCollectionTouch = 0x1;
static constexpr uint32_t kSwifterKitHIDCollectionInRange = 0x2;
static constexpr uint32_t kSwifterKitHIDCollectionStateFlagsAll = 0x3;
static constexpr uint32_t kSwifterKitHIDCollectionChangeTouch = 0x1;
static constexpr uint32_t kSwifterKitHIDCollectionChangePosition = 0x2;
static constexpr uint32_t kSwifterKitHIDCollectionChangeRange = 0x4;
static constexpr uint32_t kSwifterKitHIDCollectionChangesAll = 0x7;
static constexpr uint32_t kSwifterKitHIDCollectionChangeShift = 2;
static constexpr uint32_t kSwifterKitHIDCollectionFlagsAll = 0x1F;
static constexpr uint32_t kSwifterKitHIDGameControllerThumbstickButtonLeft = 0x1;
static constexpr uint32_t kSwifterKitHIDGameControllerThumbstickButtonRight = 0x2;
static constexpr uint32_t kSwifterKitHIDGameControllerFlagsAll = 0x3;

static constexpr uint32_t kSwifterKitNetworkMaximumBatch = 32;
static constexpr uint32_t kSwifterKitNetworkEventHeaderSize = 16;
static constexpr uint32_t kSwifterKitNetworkTransmitMetadataSize = 72;
static constexpr uint32_t kSwifterKitNetworkQueueCount = 4;
static constexpr uint64_t kSwifterKitEthernetMaximumPollInterval = 1000000000ULL;
static constexpr uint32_t kSwifterKitEthernetTapInput = 1;
static constexpr uint32_t kSwifterKitEthernetTapOutput = 2;

static constexpr uint32_t kSwifterKitNetworkEventInterfaceEnabled = 1;
static constexpr uint32_t kSwifterKitNetworkEventTransmit = 2;
static constexpr uint32_t kSwifterKitNetworkEventPromiscuousMode = 3;
static constexpr uint32_t kSwifterKitNetworkEventMulticastAddresses = 4;
static constexpr uint32_t kSwifterKitNetworkEventAllMulticastMode = 5;
static constexpr uint32_t kSwifterKitNetworkEventWakeOnMagicPacket = 6;
static constexpr uint32_t kSwifterKitNetworkEventMaximumTransferUnit = 7;
static constexpr uint32_t kSwifterKitNetworkEventHardwareAssists = 8;
static constexpr uint32_t kSwifterKitNetworkEventSelectedMedia = 9;
static constexpr uint32_t kSwifterKitNetworkEventPowerState = 10;
static constexpr uint32_t kSwifterKitNetworkEventHardwareAddress = 11;
static constexpr uint32_t kSwifterKitNetworkEventHardwareAssistsChanged = 12;
static constexpr uint32_t kSwifterKitNetworkEventPolling = 13;
static constexpr uint32_t kSwifterKitNetworkEventPacketTap = 14;
static constexpr uint32_t kSwifterKitNetworkEventNICProxyConfiguration = 15;
static constexpr uint32_t kSwifterKitNetworkEventInterfaceCommand = 16;

static constexpr uint32_t kSwifterKitNetworkPacketLinkMulticast = 0x0001;
static constexpr uint32_t kSwifterKitNetworkPacketLinkBroadcast = 0x0002;
static constexpr uint32_t kSwifterKitNetworkPacketTimestampRequested = 0x0004;
static constexpr uint32_t kSwifterKitNetworkPacketTrafficBackground = 0x0008;
static constexpr uint32_t kSwifterKitNetworkPacketTrafficRealtime = 0x0010;
static constexpr uint32_t kSwifterKitNetworkPacketHasTimestamp = 0x0020;
static constexpr uint32_t kSwifterKitNetworkPacketHasExpiryTime = 0x0040;
static constexpr uint32_t kSwifterKitNetworkPacketHasVLANTag = 0x0080;
static constexpr uint32_t kSwifterKitNetworkPacketHasDataOffset = 0x0100;
static constexpr uint32_t kSwifterKitNetworkPacketHasLRO = 0x0200;
static constexpr uint32_t kSwifterKitNetworkPacketHasTraceEvent = 0x0400;
static constexpr uint32_t kSwifterKitNetworkPacketWake = 0x0800;
static constexpr uint32_t kSwifterKitNetworkTransmitFlags = 0x00FF;
static constexpr uint32_t kSwifterKitNetworkReceiveFlags = 0x0FA1;
static constexpr uint32_t kSwifterKitNetworkCompletionFlags = 0x0420;
static constexpr uint32_t kSwifterKitNetworkRxChecksumFlags = 0x0F00;
static constexpr uint32_t kSwifterKitNetworkLROFlags = 0x0003;

static constexpr uint32_t kSwifterKitAudioObjectTableCount = 4;
static constexpr uint32_t kSwifterKitAudioPendingRequestCount = 8;
static constexpr uint32_t kSwifterKitAudioMaximumSampleRates = 64;
static constexpr uint32_t kSwifterKitAudioMaximumSettableSampleRates = 16;
static constexpr uint32_t kSwifterKitAudioNameMaximumLength = 255;
static constexpr uint32_t kSwifterKitAudioCustomPropertyValueMaximumLength = 4096;
static constexpr uint32_t kSwifterKitAudioMaximumChangedProperties = 32;
static constexpr uint32_t kSwifterKitAudioMaximumStreams = 8;
static constexpr uint32_t kSwifterKitAudioMaximumControls = 64;
static constexpr uint32_t kSwifterKitAudioMaximumCustomProperties = 32;
static constexpr uint32_t kSwifterKitAudioMaximumStreamFormats = 16;
static constexpr uint32_t kSwifterKitAudioMaximumSelectorItems = 32;
static constexpr uint32_t kSwifterKitAudioMaximumChannelLabels = 64;
static constexpr uint32_t kSwifterKitAudioMinimumZeroTimestampPeriod = 16;
static constexpr uint32_t kSwifterKitAudioMaximumFrameCount = 1048576;
static constexpr uint32_t kSwifterKitAudioMaximumRingBufferSize = 16777216;
static constexpr uint32_t kSwifterKitAudioMaximumReadLength = 65512;
static constexpr uint32_t kSwifterKitAudioMaximumWriteLength = 65472;
static constexpr uint32_t kSwifterKitAudioTransferHeaderSize = 24;
static constexpr double kSwifterKitAudioMinimumSampleRate = 8000.0;
static constexpr double kSwifterKitAudioMaximumSampleRate = 768000.0;

static constexpr uint32_t kSwifterKitAudioTargetDriver = 0;
static constexpr uint32_t kSwifterKitAudioTargetDevice = 1;
static constexpr uint32_t kSwifterKitAudioTargetBox = 2;
static constexpr uint32_t kSwifterKitAudioTargetClock = 3;
static constexpr uint32_t kSwifterKitAudioTargetObject = 4;
static constexpr uint32_t kSwifterKitAudioOwnerDetached = 0;
static constexpr uint32_t kSwifterKitAudioOwnerDevice = 1;
static constexpr uint32_t kSwifterKitAudioOwnerDriver = 2;
static constexpr uint32_t kSwifterKitAudioElementName = 0;
static constexpr uint32_t kSwifterKitAudioElementCategory = 1;
static constexpr uint32_t kSwifterKitAudioElementNumber = 2;
static constexpr uint32_t kSwifterKitAudioMemberStream = 1;
static constexpr uint32_t kSwifterKitAudioMemberControl = 2;
static constexpr uint32_t kSwifterKitAudioMemberCustomProperty = 3;

static constexpr uint32_t kSwifterKitAudioEventStarted = 1;
static constexpr uint32_t kSwifterKitAudioEventStopped = 2;
static constexpr uint32_t kSwifterKitAudioEventSampleRateChanged = 3;
static constexpr uint32_t kSwifterKitAudioEventControlChanged = 4;
static constexpr uint32_t kSwifterKitAudioEventCustomPropertyChanged = 5;
static constexpr uint32_t kSwifterKitAudioObjectEventDeviceStarted = 1;
static constexpr uint32_t kSwifterKitAudioObjectEventDeviceStopped = 2;
static constexpr uint32_t kSwifterKitAudioObjectEventClockStarted = 3;
static constexpr uint32_t kSwifterKitAudioObjectEventClockStopped = 4;
static constexpr uint32_t kSwifterKitAudioObjectEventClockRateChanged = 5;
static constexpr uint32_t kSwifterKitAudioObjectEventBoxRequest = 6;
static constexpr uint32_t kSwifterKitAudioObjectEventClockRequest = 7;

static constexpr uint32_t kSwifterKitAudioValueBoolean = 1;
static constexpr uint32_t kSwifterKitAudioValueDecibels = 2;
static constexpr uint32_t kSwifterKitAudioValueScalar = 3;
static constexpr uint32_t kSwifterKitAudioValueSelector = 4;
static constexpr uint32_t kSwifterKitAudioValueSlider = 5;
static constexpr uint32_t kSwifterKitAudioValueStereoPan = 6;
static constexpr uint32_t kSwifterKitAudioControlBoolean = 1;
static constexpr uint32_t kSwifterKitAudioControlLevel = 2;
static constexpr uint32_t kSwifterKitAudioControlSelector = 3;
static constexpr uint32_t kSwifterKitAudioControlSlider = 4;
static constexpr uint32_t kSwifterKitAudioControlStereoPan = 5;

static constexpr uint32_t kSwifterKitAudioDevicePropertyCanBeDefaultInput = 1;
static constexpr uint32_t kSwifterKitAudioDevicePropertyCanBeDefaultOutput = 2;
static constexpr uint32_t kSwifterKitAudioDevicePropertyCanBeDefaultSystemOutput = 3;
static constexpr uint32_t kSwifterKitAudioDevicePropertyInputSafetyOffset = 4;
static constexpr uint32_t kSwifterKitAudioDevicePropertyOutputSafetyOffset = 5;
static constexpr uint32_t kSwifterKitAudioDevicePropertyPreferredStereoChannels = 6;
static constexpr uint32_t kSwifterKitAudioDevicePropertyWantsStreamFormatsRestored = 7;
static constexpr uint32_t kSwifterKitAudioStreamPropertyIsActive = 1;
static constexpr uint32_t kSwifterKitAudioStreamPropertyLatency = 2;
static constexpr uint32_t kSwifterKitAudioStreamPropertyStartingChannel = 3;
static constexpr uint32_t kSwifterKitAudioStreamPropertyTerminalType = 4;
static constexpr uint32_t kSwifterKitAudioStreamPropertyCurrentFormat = 5;
static constexpr uint32_t kSwifterKitAudioStreamPropertyRingBufferFrameCapacity = 6;
static constexpr uint32_t kSwifterKitAudioControlPropertySliderRange = 1;
static constexpr uint32_t kSwifterKitAudioControlPropertyPanningChannels = 2;
static constexpr uint32_t kSwifterKitAudioBoxPropertyTransport = 1;
static constexpr uint32_t kSwifterKitAudioBoxPropertyHasAudio = 2;
static constexpr uint32_t kSwifterKitAudioBoxPropertyHasMIDI = 3;
static constexpr uint32_t kSwifterKitAudioBoxPropertyHasVideo = 4;
static constexpr uint32_t kSwifterKitAudioBoxPropertyIsAcquirable = 5;
static constexpr uint32_t kSwifterKitAudioBoxPropertyIsAcquired = 6;
static constexpr uint32_t kSwifterKitAudioBoxPropertyIsProtected = 7;
static constexpr uint32_t kSwifterKitAudioBoxPropertyAcquisitionFailure = 8;
static constexpr uint32_t kSwifterKitAudioClockPropertyClockDomain = 1;
static constexpr uint32_t kSwifterKitAudioClockPropertyClockAlgorithm = 2;
static constexpr uint32_t kSwifterKitAudioClockPropertyClockIsStable = 3;
static constexpr uint32_t kSwifterKitAudioClockPropertyIsAlive = 4;
static constexpr uint32_t kSwifterKitAudioClockPropertyIsHidden = 5;
static constexpr uint32_t kSwifterKitAudioClockPropertyInputLatency = 6;
static constexpr uint32_t kSwifterKitAudioClockPropertyOutputLatency = 7;
static constexpr uint32_t kSwifterKitAudioClockPropertyTransport = 8;
static constexpr uint32_t kSwifterKitAudioClockPropertyZeroTimestampPeriod = 9;
static constexpr uint32_t kSwifterKitAudioClockPropertyWantsControlsRestored = 10;

static constexpr uint32_t kSwifterKitAudioBoxStateHasAudio = 0x1;
static constexpr uint32_t kSwifterKitAudioBoxStateHasMIDI = 0x2;
static constexpr uint32_t kSwifterKitAudioBoxStateHasVideo = 0x4;
static constexpr uint32_t kSwifterKitAudioBoxStateIsAcquirable = 0x8;
static constexpr uint32_t kSwifterKitAudioBoxStateIsAcquired = 0x10;
static constexpr uint32_t kSwifterKitAudioBoxStateIsProtected = 0x20;
static constexpr uint32_t kSwifterKitAudioBoxStateAll = 0x3F;
static constexpr uint32_t kSwifterKitAudioClockStateClockIsStable = 0x1;
static constexpr uint32_t kSwifterKitAudioClockStateIsAlive = 0x2;
static constexpr uint32_t kSwifterKitAudioClockStateIsRunning = 0x4;
static constexpr uint32_t kSwifterKitAudioClockStateIsHidden = 0x8;
static constexpr uint32_t kSwifterKitAudioClockStateSupportsPrewarming = 0x10;
static constexpr uint32_t kSwifterKitAudioClockStateAll = 0x1F;

static constexpr uint32_t kSwifterKitVideoObjectTableCount = 4;
static constexpr uint32_t kSwifterKitVideoPendingRequestCount = 8;
static constexpr uint32_t kSwifterKitVideoMaximumSampleRates = 16;
static constexpr uint32_t kSwifterKitVideoNameMaximumLength = 255;
static constexpr uint32_t kSwifterKitVideoCustomPropertyValueMaximumLength = 4096;
static constexpr uint32_t kSwifterKitVideoMaximumChangedProperties = 32;
static constexpr uint32_t kSwifterKitVideoMaximumStreams = 8;
static constexpr uint32_t kSwifterKitVideoMaximumBuffers = 32;
static constexpr uint32_t kSwifterKitVideoMaximumControls = 64;
static constexpr uint32_t kSwifterKitVideoMaximumCustomProperties = 32;
static constexpr uint32_t kSwifterKitVideoMaximumStreamFormats = 16;
static constexpr uint32_t kSwifterKitVideoMaximumSelectorItems = 32;
static constexpr uint32_t kSwifterKitVideoMaximumChannelLabels = 64;
static constexpr uint32_t kSwifterKitVideoMaximumQueueEntries = 256;
static constexpr uint32_t kSwifterKitVideoMaximumDataCapacity = 67108864;
static constexpr uint32_t kSwifterKitVideoMaximumControlCapacity = 1048576;
static constexpr uint32_t kSwifterKitVideoTransferHeaderSize = 32;
static constexpr uint32_t kSwifterKitVideoMaximumReadLength = 65464;
static constexpr uint32_t kSwifterKitVideoMaximumWriteLength = 65432;

static constexpr uint32_t kSwifterKitVideoTargetDriver = 0;
static constexpr uint32_t kSwifterKitVideoTargetDevice = 1;
static constexpr uint32_t kSwifterKitVideoTargetBox = 2;
static constexpr uint32_t kSwifterKitVideoTargetClock = 3;
static constexpr uint32_t kSwifterKitVideoTargetObject = 4;
static constexpr uint32_t kSwifterKitVideoOwnerDetached = 0;
static constexpr uint32_t kSwifterKitVideoOwnerDevice = 1;
static constexpr uint32_t kSwifterKitVideoOwnerDriver = 2;
static constexpr uint32_t kSwifterKitVideoElementName = 0;
static constexpr uint32_t kSwifterKitVideoElementCategory = 1;
static constexpr uint32_t kSwifterKitVideoElementNumber = 2;
static constexpr uint32_t kSwifterKitVideoMemberStream = 1;
static constexpr uint32_t kSwifterKitVideoMemberControl = 2;
static constexpr uint32_t kSwifterKitVideoNotifyBufferQueueChange = 1;
static constexpr uint32_t kSwifterKitVideoNotifyOutputBufferNotification = 2;
static constexpr uint32_t kSwifterKitVideoNotifyStreamBufferQueueChange = 3;
static constexpr uint32_t kSwifterKitVideoDirectionOutput = 0;
static constexpr uint32_t kSwifterKitVideoDirectionInput = 1;
static constexpr uint32_t kSwifterKitVideoPlaneData = 0;
static constexpr uint32_t kSwifterKitVideoPlaneControl = 1;

static constexpr uint32_t kSwifterKitVideoEventStarted = 1;
static constexpr uint32_t kSwifterKitVideoEventStopped = 2;
static constexpr uint32_t kSwifterKitVideoEventSampleRateChanged = 3;
static constexpr uint32_t kSwifterKitVideoEventControlChanged = 4;
static constexpr uint32_t kSwifterKitVideoEventCustomPropertyChanged = 5;
static constexpr uint32_t kSwifterKitVideoEventStreamStarted = 6;
static constexpr uint32_t kSwifterKitVideoEventStreamStopped = 7;
static constexpr uint32_t kSwifterKitVideoEventStreamFormatChanged = 8;
static constexpr uint32_t kSwifterKitVideoEventStreamActiveChanged = 9;
static constexpr uint32_t kSwifterKitVideoEventStreamInputAvailable = 10;
static constexpr uint32_t kSwifterKitVideoObjectEventDeviceStarted = 1;
static constexpr uint32_t kSwifterKitVideoObjectEventDeviceStopped = 2;
static constexpr uint32_t kSwifterKitVideoObjectEventClockStarted = 3;
static constexpr uint32_t kSwifterKitVideoObjectEventClockStopped = 4;
static constexpr uint32_t kSwifterKitVideoObjectEventClockRateChanged = 5;
static constexpr uint32_t kSwifterKitVideoObjectEventBoxRequest = 6;
static constexpr uint32_t kSwifterKitVideoObjectEventClockRequest = 7;
static constexpr uint32_t kSwifterKitVideoObjectEventClockFormatChanged = 8;
static constexpr uint32_t kSwifterKitVideoObjectEventDeviceFormatChanged = 9;

static constexpr uint32_t kSwifterKitVideoValueBoolean = 1;
static constexpr uint32_t kSwifterKitVideoValueDecibels = 2;
static constexpr uint32_t kSwifterKitVideoValueScalar = 3;
static constexpr uint32_t kSwifterKitVideoValueSelector = 4;
static constexpr uint32_t kSwifterKitVideoValueSlider = 5;
static constexpr uint32_t kSwifterKitVideoValueStereoPan = 6;
static constexpr uint32_t kSwifterKitVideoValueDirection = 7;
static constexpr uint32_t kSwifterKitVideoControlBoolean = 1;
static constexpr uint32_t kSwifterKitVideoControlLevel = 2;
static constexpr uint32_t kSwifterKitVideoControlSelector = 3;
static constexpr uint32_t kSwifterKitVideoControlSlider = 4;
static constexpr uint32_t kSwifterKitVideoControlStereoPan = 5;
static constexpr uint32_t kSwifterKitVideoControlDirection = 6;

static constexpr uint32_t kSwifterKitVideoDevicePropertyCanBeDefaultInput = 1;
static constexpr uint32_t kSwifterKitVideoDevicePropertyCanBeDefaultOutput = 2;
static constexpr uint32_t kSwifterKitVideoDevicePropertyCanBeDefaultSystemOutput = 3;
static constexpr uint32_t kSwifterKitVideoDevicePropertyInputSafetyOffset = 4;
static constexpr uint32_t kSwifterKitVideoDevicePropertyOutputSafetyOffset = 5;
static constexpr uint32_t kSwifterKitVideoDevicePropertyPreferredStereoChannels = 6;
static constexpr uint32_t kSwifterKitVideoStreamPropertyIsActive = 1;
static constexpr uint32_t kSwifterKitVideoStreamPropertyStartingChannel = 2;
static constexpr uint32_t kSwifterKitVideoStreamPropertyTerminalType = 3;
static constexpr uint32_t kSwifterKitVideoStreamPropertyCurrentFormat = 4;
static constexpr uint32_t kSwifterKitVideoStreamPropertyBufferCapacity = 5;
static constexpr uint32_t kSwifterKitVideoStreamPropertyQueueEntryCount = 6;
static constexpr uint32_t kSwifterKitVideoBufferPropertyBufferID = 1;
static constexpr uint32_t kSwifterKitVideoBufferPropertyIsAttached = 2;
static constexpr uint32_t kSwifterKitVideoControlPropertySliderRange = 1;
static constexpr uint32_t kSwifterKitVideoControlPropertyPanningChannels = 2;
static constexpr uint32_t kSwifterKitVideoBoxPropertyTransport = 1;
static constexpr uint32_t kSwifterKitVideoBoxPropertyHasAudio = 2;
static constexpr uint32_t kSwifterKitVideoBoxPropertyHasMIDI = 3;
static constexpr uint32_t kSwifterKitVideoBoxPropertyHasVideo = 4;
static constexpr uint32_t kSwifterKitVideoBoxPropertyIsAcquirable = 5;
static constexpr uint32_t kSwifterKitVideoBoxPropertyIsAcquired = 6;
static constexpr uint32_t kSwifterKitVideoBoxPropertyIsProtected = 7;
static constexpr uint32_t kSwifterKitVideoBoxPropertyAcquisitionFailure = 8;
static constexpr uint32_t kSwifterKitVideoClockPropertyClockDomain = 1;
static constexpr uint32_t kSwifterKitVideoClockPropertyClockAlgorithm = 2;
static constexpr uint32_t kSwifterKitVideoClockPropertyClockIsStable = 3;
static constexpr uint32_t kSwifterKitVideoClockPropertyIsAlive = 4;
static constexpr uint32_t kSwifterKitVideoClockPropertyIsHidden = 5;
static constexpr uint32_t kSwifterKitVideoClockPropertyInputLatency = 6;
static constexpr uint32_t kSwifterKitVideoClockPropertyOutputLatency = 7;
static constexpr uint32_t kSwifterKitVideoClockPropertyTransport = 8;

static constexpr uint32_t kSwifterKitVideoBoxStateHasAudio = 0x1;
static constexpr uint32_t kSwifterKitVideoBoxStateHasMIDI = 0x2;
static constexpr uint32_t kSwifterKitVideoBoxStateHasVideo = 0x4;
static constexpr uint32_t kSwifterKitVideoBoxStateIsAcquirable = 0x8;
static constexpr uint32_t kSwifterKitVideoBoxStateIsAcquired = 0x10;
static constexpr uint32_t kSwifterKitVideoBoxStateIsProtected = 0x20;
static constexpr uint32_t kSwifterKitVideoBoxStateAll = 0x3F;
static constexpr uint32_t kSwifterKitVideoClockStateClockIsStable = 0x1;
static constexpr uint32_t kSwifterKitVideoClockStateIsAlive = 0x2;
static constexpr uint32_t kSwifterKitVideoClockStateIsRunning = 0x4;
static constexpr uint32_t kSwifterKitVideoClockStateIsHidden = 0x8;
static constexpr uint32_t kSwifterKitVideoClockStateAll = 0xF;

#endif
